[build]
  # This is the directory that contains the files to be published
  publish = "."
  
[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
